# Generated by Django 4.2.7 on 2023-11-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_obj",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="actions_act_created_64f10d_idx"
                    ),
                    models.Index(
                        fields=["target_ct", "target_id"],
                        name="actions_act_target__f20513_idx",
                    ),
                ],
            },
        ),
    ]
