# Generated by Django 4.2.7 on 2023-11-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nudls_system.zone"
            ),
        ),
        migrations.CreateModel(
            name="DragonFed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "dragon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_dragon_fed",
                        to="nudls_system.dragon",
                    ),
                ),
            ],
        ),
    ]
