# Generated by Django 4.2.7 on 2023-11-16 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0002_alter_location_location_dragonfed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="DragonLocation",
        ),
    ]
