# Generated by Django 4.2.7 on 2023-11-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0003_rename_location_dragonlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dragonlocation",
            name="dragon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dragon_location",
                to="nudls_system.dragon",
            ),
        ),
        migrations.AlterField(
            model_name="dragonlocation",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="nudls_system.zone"
            ),
        ),
    ]
