# Generated by Django 4.2.7 on 2023-11-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0004_alter_dragonlocation_dragon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dragonlocation",
            name="id",
        ),
        migrations.AlterField(
            model_name="dragonlocation",
            name="dragon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="dragon_location",
                serialize=False,
                to="nudls_system.dragon",
            ),
        ),
    ]
