# Generated by Django 4.2.7 on 2023-11-16 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0007_alter_dragon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="maintainence_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 16, 13, 4, 34, 931585)
            ),
        ),
    ]
