# Generated by Django 4.2.7 on 2023-11-16 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nudls_system", "0008_zone_maintainence_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="maintainence_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 16, 13, 32, 48, 821479)
            ),
        ),
    ]
